spring.application.name=UserService

spring.datasource.url=jdbc:postgresql://localhost:5432/user
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=b3JkZXIgbWFuYWdlciBkcml2ZW4gZXZlbnQgYXJjaGl0ZWN0dXJlIGphdmEgYXBwbGljYXRpb24=
jwt.expiration-ms=3600000
kafka.topics.user-created=user-created
kafka.topics.user-updated=user-updated
kafka.topics.user-deleted=user-deleted

server.port=8080